import days

print(days.sun)
p1=days.Person(name='robert',age=30)
print(p1)
s1=days.Student(name='邱育霖',age=40,chinese=85,english=79,math=71)
print(s1.name)
print(s1.age)
print(s1.english)
print(s1.math)
print(s1.chinese)
print(s1.total)
print(s1.average())
print('================')
p2=days.get_person("邱xx",23)
print(p2)
s2=days.get_student(name='徐xx',age=43)
print(s2)
print(s2.total)
print(s2.average())